"""Generated from Jupyter notebook: Sparse Modeling Time Series FRED Data

Magics and shell lines are commented out. Run with a normal Python interpreter."""


# --- code cell ---

from datetime import datetimefrom pandas_datareader.data import DataReaderfrom sklearn.metrics import mean_squared_errorfrom sklearn.preprocessing import StandardScalerimport osfrom sklearn.linear_model import LassoCVfrom sklearn.model_selection import TimeSeriesSplitfrom sklearn.pipeline import make_pipelineimport matplotlib.pyplot as pltimport pandas as pd# Create directory structurebase_dir = "article - 2025 - 06 - 27 - sparse - modeling - time - series"os.makedirs(base_dir, exist_ok = True)os.makedirs(f"{base_dir}/images", exist_ok = True)# Create sparse_modeling.py scriptcode = """def fetch_fred(series_ids, start='2000 - 01 - 01'):df = pd.DataFrame()for series in series_ids:data = DataReader(series, 'fred', start)data = data.rename(columns={series: series.lower()})df = pd.concat([df, data], axis = 1)return df.dropna()def create_lag_features(df, lags=[1, 2, 3]):lagged = df.copy()for col in df.columns:for lag in lags:lagged[f'{col}_lag{lag}'] = df[col].shift(lag)return lagged.dropna()if __name__ == "__main__":series_list = ['WTISPLC', 'CPIAUCNS', 'INDPRO', 'UNRATE', 'T10Y2Y']df = fetch_fred(series_list)df = df.resample('M').mean().dropna()df_lagged = create_lag_features(df)target = 'wtisplc'X = df_lagged.drop(columns=[target])y = df_lagged[target]tscv = TimeSeriesSplit(n_splits = 5)model = make_pipeline(StandardScaler(), LassoCV(cv = tscv, max_iter = 10000))model.fit(X, y)pred = model.predict(X)mse = mean_squared_error(y, pred)print(f'Mean Squared Error: {mse:.2f}')# Plot selected featureslasso = model.named_steps['lassocv']coef = pd.Series(lasso.coef_, index = X.columns)selected = coef[coef != 0]plt.figure(figsize=(10, 4))selected.sort_values().plot(kind='barh')plt.title('Selected Features (Non - Zero Coefficients)')plt.tight_layout()plt.savefig('images / lasso_selected_features.png')plt.show()# Plot forecastplt.figure(figsize=(12, 4))plt.plot(y.index, y, label='Actual')plt.plot(y.index, pred, label='LASSO Forecast', alpha = 0.7)plt.title('Crude Oil Price Forecast with Sparse Regression')plt.legend()plt.tight_layout()plt.savefig('images / lasso_forecast.png')plt.show()"""with open(f"{base_dir}/sparse_modeling.py", "w") as f:f.write(code)# Create README.mdreadme = """# Sparse Modeling for Time Series Forecasting in PythonThis article demonstrates how to use LASSO regression for sparse forecasting of crude oil prices using macroeconomic indicators from FRED.## Files- `sparse_modeling.py`: Main script that fetches FRED data,    creates lag features,    trains a LASSO model,    and plots results.- `images/`: Contains saved plots of selected features and forecast results.## Dependencies- pandas- pandas_datareader- matplotlib- scikit - learn"""with open(f"{base_dir}/README.md", "w") as f:f.write(readme)# Create requirements.txtrequirements = """pandaspandas_datareadermatplotlibscikit - learn"""with open(f"{base_dir}/requirements.txt", "w") as f:f.write(requirements)base_dir


# --- code cell ---

def fetch_fred(series_ids, start="2000 - 01 - 01"):df = pd.DataFrame()for series in series_ids:data = DataReader(series, "fred", start)data = data.rename(columns={series: series.lower()})df = pd.concat([df, data], axis = 1)return df.dropna()def create_lag_features(df, lags=[1, 2, 3]):lagged = df.copy()for col in df.columns:for lag in lags:lagged[f"{col}_lag{lag}"] = df[col].shift(lag)return lagged.dropna()if __name__ == "__main__":series_list = ["WTISPLC", "CPIAUCNS", "INDPRO", "UNRATE", "T10Y2Y"]df = fetch_fred(series_list)df = df.resample("ME").mean().dropna()df_lagged = create_lag_features(df)target = "wtisplc"X = df_lagged.drop(columns=[target])y = df_lagged[target]tscv = TimeSeriesSplit(n_splits = 5)model = make_pipeline(StandardScaler(), LassoCV(cv = tscv, max_iter = 10000))model.fit(X, y)pred = model.predict(X)mse = mean_squared_error(y, pred)print(f"Mean Squared Error: {mse:.2f}")# Plot selected featureslasso = model.named_steps["lassocv"]coef = pd.Series(lasso.coef_, index = X.columns)selected = coef[coef != 0]plt.figure(figsize=(10, 4))selected.sort_values().plot(kind="barh")plt.title("Selected Features (Non - Zero Coefficients)")plt.tight_layout()plt.savefig("article - 2025 - 06 - 27 - sparse - modeling - time - series / images / lasso_selected_features.png")plt.show()# Plot forecastplt.figure(figsize=(12, 4))plt.plot(y.index, y, label="Actual")plt.plot(y.index, pred, label="LASSO Forecast", alpha = 0.7)plt.title("Crude Oil Price Forecast with Sparse Regression")plt.legend()plt.tight_layout()plt.savefig("article - 2025 - 06 - 27 - sparse - modeling - time - series / images / lasso_forecast.png")plt.show()
